apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: capture
spec:
  template:
    metadata:
      labels:
        app: logging-app
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux 
      hostNetwork: true  
      containers:
        - name: capture-proxy
          image: dinorg/prolog
          command: ["/bin/sh"]
          args: ["-c","while $(true); do cp /var/log/pods/$UID/kube-proxy/*.* /mnt/azure/plogshare/$MY_NODE_NAME; done"]
          #for 1.14 uncomment:
          #args: ["-c","while $(true); do cp /var/log/pods/$UID/kube-proxy/*.* /mnt/azure/plogshare/$MY_NODE_NAME; done"]
          ##UID=kube-system_kube-proxy*          
          # for 1.14 the directory struction is /var/log/pods
        # default_dnstest-85f69986b-nk7ls_11364d2b-8eaa-11e9-960f-c2c752b96b98
        # default_nginx-755464dd6c-6476g_acd6c3e8-8c12-11e9-bb61-6e8b42ef29ec
        # default_zinc-snake-nginx-ingress-controller-55858ff67f-24wfq_4f03f656-8c14-11e9-bb61-6e8b42ef29ec
        # default_zinc-snake-nginx-ingress-default-backend-7b9f5596fb-5kfsf_4f0c6012-8c14-11e9-bb61-6e8b42ef29ec
        # kube-system_coredns-85c4d4c5d8-5b24b_667f2f49-8971-11e9-9b85-0632058a0a5a
        # kube-system_coredns-85c4d4c5d8-ftczg_669af223-8971-11e9-9b85-0632058a0a5a
        # kube-system_coredns-autoscaler-7b6f68868f-w2sfs_665d91b3-8971-11e9-9b85-0632058a0a5a
        # ns_podname_guid
              
             
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: UID
            value: {{ .Values.guid }}
          volumeMounts:
          - mountPath: /var/lib/docker/containers/
            name: plogs
            readOnly: false
          - mountPath: /var/log/pods/{{ .Values.guid }}/kube-proxy
            name: dock
            readOnly: false
          - mountPath: /mnt/azure/plogshare
            name: azure
            readOnly: false
      volumes:     
      - hostPath:
          path: /var/lib/docker/containers/
          type: ""
        name: plogs
      - hostPath: 
          path: /var/log/pods/{{ .Values.guid }}/kube-proxy
          type: ""
        name: dock  
      - name: azure
        persistentVolumeClaim:
          claimName: azurefile

           
